[package]
name = "gboxide"
version = "0.1.0"
authors = ["StarlitGhost <36834781+StarlitGhost@users.noreply.github.com>"]

[dependencies]
bitflags = "1.0.1"
byteorder = "1"
clap = {version = "2.30", features = ["yaml"]}
glium = "0.20"
imgui = "0.0.18"
imgui-glium-renderer = "0.0.18"